### PR TITLE
Fix: Updated `completionCalculations.js` (fixes #10)

### LINKED ISSUE #10: `completionCalculations.js` file requires update
### Subject of the issue
The `completionCalculations.js` file is out of date compared to the equivalent file in the Page Level Progress plugin.

### Your environment
* FW Master
* ToC v1.0.1

### Expected behaviour
Copy the latest `completionCalculations.js` file from PLP and overwrite ToC's current version.

### PR DESCRIPTION
**Pull request by guywillis**
Fixes: #10 

### Fix
* Overwrote ToC `completionCalculations.js` with equivalent file from PLP v7.2.3

### CODE REVIEW

File: js/completionCalculations.js [hunk 1]
```diff
@@ -1,149 +1,141 @@
...
-  return {
-    calculateCompletion: calculateCompletion,
-    calculatePercentageComplete: calculatePercentageComplete,
-    getPageLevelProgressEnabledModels: getPageLevelProgressEnabledModels,
-    filterAvailableChildren: filterAvailableChildren
-  };
+}
 
-});
+export default (Adapt.completion = new Completion());
```
Comment (oliverfoster) [inline js/completionCalculations.js]: You probably want to replace all `Adapt.completion` with `Adapt.tocCompletion`, save plp and toc interfering with each other.

**Comment by oliverfoster** [comment]
If you need @chris-steele to review @guywillis you probably want to ping him a message on teams. He doesn't seem to get comms from github.

**Review by oliverfoster — APPROVED** [review]

**Review by chris-steele — APPROVED** [review]
